spring:
  datasource:
    driver-class-name: ENC(sjlqxCVFpyNWKD/vjlhrtpateI8ptocSVOba6EJtiqYf/C6V1vRwOw==)
    url: ENC(QhZoF+5/4nRzDpCPQWIHdXnkA4vcgaRu1gtDGvTQi/a7ZPaF25XCTw==)
    username: ENC(cYB2Olb6VXWi5jHFUIsl4w==)
    password: ENC(9cdu1LZgayPrMOBofUI9yg==)
    hikari:
      maximumPoolSize: 3

  data:
    mongodb:
      uri: mongodb://localhost:27017/mydb

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(rL5BS6PCrTZ5IAJqBlXEEKI1HmjeXEoIiiyG56bix18=)
    password: ENC(+FD8zxyH8mWCMPdtQOLqL7P6TFhDqjSLlPI//XQelNo=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false


server:
  servlet:
    context-path: /