spring:
  datasource:
    driver-class-name: ENC(sjlqxCVFpyNWKD/vjlhrtpateI8ptocSVOba6EJtiqYf/C6V1vRwOw==)
    url: ENC(QhZoF+5/4nRzDpCPQWIHdXnkA4vcgaRu1gtDGvTQi/a7ZPaF25XCTw==)
    username: ENC(cYB2Olb6VXWi5jHFUIsl4w==)
    password: ENC(9cdu1LZgayPrMOBofUI9yg==)
    hikari:
      maximumPoolSize: 3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(rL5BS6PCrTZ5IAJqBlXEEKI1HmjeXEoIiiyG56bix18=)
    password: ENC(+FD8zxyH8mWCMPdtQOLqL7P6TFhDqjSLlPI//XQelNo=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password: ssafy1234!!

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    context-path: /

cloud:
  aws:
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: laams
    credentials:
      access-key: 8scKCA8RIIv7UmfxCDud
      secret-key: Ijm4NfDuwt6fTeDrUT0mdOH1KTQdRY00xHhvKOF1
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false